### ISSUE TITLE
Model improvement for settlements

### ISSUE THREAD

**Issue by bernardyn** [ontohgis/wikikul#13]
We need to add 
1 classes like: 
* folwark (demesne), 
* miasto (city / town), 
* wieś (village)
as a subClassOf [proper dwelling](https://wiki.kul.pl/wiki/Item:Q3)

2 
* klasztor - obiekt (monastery) as a subClassOf budynek mieszkalny (housing building)

3
* kaplica - obiekt (chapel) as a subClassOf budynek (building)

4 
* kościół filialny
* kościół katedralny
* kościół kolegiacki
* kościół szpitalny
as a subClassOf kościół - obiekt (church)

**Comment by bszady** [comment]
ok
