### ISSUE TITLE
Create properties and base classes to import settlements

### ISSUE THREAD

**Issue by bernardyn** [ontohgis/wikikul#14]
We need to have a properties and main entities before settlements import
1. subClassOf - property
2. budynek mieszkalny (housing building) - item
3. budynek (building)
4. kościół - obiekt (church)

**Comment by mereolog** [comment]
You do have it - it is http://www.w3.org/2000/01/rdf-schema#subClassOf.

**Comment by bernardyn** [comment]
We need it as a wiki property on prod - https://wiki.kul.pl/wiki/Special:ListProperties
